---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: calm-operator-system
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - measurement.calm.com
  resources:
  - latencymeasurements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - measurement.calm.com
  resources:
  - latencymeasurements/finalizers
  verbs:
  - update
- apiGroups:
  - measurement.calm.com
  resources:
  - latencymeasurements/status
  verbs:
  - get
  - patch
  - update
